### ISSUE TITLE
Update to 7.0.0 Please!

### ISSUE THREAD

**Issue by sensei73** [lvgl/lv_platformio#19]
First of all, thanks for this marvelous software and congratulation in your news achievements!

I'm so exited to test out the 7.0.0 version.
But it will be Wonderfull if you could update this simulator!

Thanks in advance.

**Comment by Staars** [comment]
I did a short test with the benchmark-demo and it works for me.

You can check my fork, if you like:
https://github.com/Staars/lv_platformio

**Comment by mbrdar** [comment]
@Staars thanks a lot it works! Whit lvgl 7.7.2 version I got some errors in printer demo but I just removed that demo end project is compiling and working perfectly!

**Comment by bjwschaap** [comment]
I've updated this repo to the most recent LVGL version, and provided pull request #26
