### ISSUE TITLE
Something wrong in package manager

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lv_platformio#21]
Hi,

I've just noticed that the library manager doesn't fetch lvgl correctly.
https://platformio.org/lib/show/6598/lvgl

Do you know why can it happen?

**Comment by puzrin** [comment]
https://travis-ci.org/github/lvgl/lv_platformio/builds/706000370

Just re-executed build tests (you can do it too anytime). All pass.

What's exactly wrong & how to reproduce?

**Comment by kisvegabor** [comment]
Versions look strange
![image](https://user-images.githubusercontent.com/7599318/86921055-d4ba7c80-c12a-11ea-97d3-b058f7bfb532.png)

All the downloads come from the last week.
![image](https://user-images.githubusercontent.com/7599318/86921181-016e9400-c12b-11ea-9a22-b1d4dfb382af.png)

So it seems something is messed up.

**Comment by embeddedt** [comment]
It seems that it's not working with the automated release script (7.0.2 has some strange prefix on it).

**Comment by kisvegabor** [comment]
I've noticed that `v` prefix was added back to the version string. 
I've removed it and updated the release script.

**Comment by puzrin** [comment]
So, as far as i understand, question is not about package manager (local tool), but about registry & it's crawler.

Then i'd suggest ask at their forum. Also note, they planned to upgrade regisry and could break something https://community.platformio.org/t/embedded-template-library-v15-x-dissappeared-from-registry/14096/5?u=vit.

**Comment by kisvegabor** [comment]
> So, as far as i understand, question is not about package manager (local tool), but about registry & it's crawler.

Ah, I see.

> Then i'd suggest ask at their forum. Also note, they planned to upgrade regisry and could break something

Let's give it a day, maybe the removed `v` prefix changes something.

**Comment by puzrin** [comment]
I see 7.1.0 in registry

**Comment by kisvegabor** [comment]
Yep, all look good after removing the `v` prefix.

Good to see that there are so many downloads from PIO too :) 

As the issue is solved I close it now. Thanks!
