### ISSUE TITLE
CI: force use more fresh compiler for `native` on OSX

### ISSUE THREAD

**Issue by puzrin** [lvgl/lv_platformio#29]
**Problem:**

- `native` (emulator) build uses default OS's gcc compiler
- gcc in OSX is VERY old (they prefer llvm)

As a result, when you try to use some modern libs like ETL, build will fail. See https://github.com/puzrin/dispenser/blob/master/.github/workflows/ci.yml#L52-L54

---

I consider this as bug of PIO, but problem still exists.

**Comment by andrew-elsayeh** [comment]
Yes, this is a good point! 

There is no gcc port for the Apple Silicone Macs (M1, M1 Pro and M1 Max)

**Comment by puzrin** [comment]
Do PR, if you know how to fix https://github.com/lvgl/lv_platformio/blob/master/.github/workflows/ci.yml#L56-L76

**Comment by bobwolff68** [comment]
After lots of gyrations, I did manage to compile and execute this project on a Mac M1. The change was simple. Add a few items to build_flags in platformio.ini
  -arch arm64
  -I /opt/homebrew/include
  -L /opt/homebrew/lib

**Comment by fbiego** [comment]
Closing this issue as it’s resolved
