### ISSUE TITLE
Update to v8 Please!

### ISSUE THREAD

**Issue by XIGUAjuice** [lvgl/lv_platformio#35]
Does anyone work on v8 simulator?

**Comment by kisvegabor** [comment]
It's great! Could you send a Pull request?

**Comment by reflector-li** [comment]
> PS. after some code change I succefully run it with v.8.0.1 here is my code: https://github.com/smarq8/lv_platformio-simulator-v8.0.1 ![LVGL simulator v 8 0 1 DEMO](https://user-images.githubusercontent.com/5141045/137637477-c473b5ed-062d-4ce8-9b30-2b6cd1eaad18.png)

Could you help me solve it ? I download your version and compile it in VS code, but it still remind that There is no <SDL/>

> PS. after some code change I succefully run it with v.8.0.1 here is my code: https://github.com/smarq8/lv_platformio-simulator-v8.0.1 ![LVGL simulator v 8 0 1 DEMO](https://user-images.githubusercontent.com/5141045/137637477-c473b5ed-062d-4ce8-9b30-2b6cd1eaad18.png)

Could you help me to solve it ? I download your version and compile it in VS code, but it still remind that "<SDL2/SDL.h>" does not exist. The message is 
`> Executing task: C:\Users\12971\.platformio\penv\Scripts\platformio.exe run <

Processing emulator_64bits (platform: native@^1.1.3)
------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 2 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <lvgl> 8.0.1
|-- <lv_drivers> 8.0.1
|   |-- <lvgl> 8.0.1
Building in release mode
Compiling .pio\build\emulator_64bits\libfaf\lvgl\core\lv_disp.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\core\lv_event.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\core\lv_group.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\core\lv_indev.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\core\lv_indev_scroll.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\core\lv_obj.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\core\lv_obj_class.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\core\lv_obj_draw.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\core\lv_obj_pos.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\core\lv_obj_scroll.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\core\lv_obj_style.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\core\lv_obj_style_gen.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\core\lv_obj_tree.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\core\lv_refr.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\core\lv_theme.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\draw\lv_draw_arc.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\draw\lv_draw_blend.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\draw\lv_draw_img.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\draw\lv_draw_label.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\draw\lv_draw_line.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\draw\lv_draw_mask.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\draw\lv_draw_rect.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\draw\lv_draw_triangle.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\draw\lv_img_buf.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\draw\lv_img_cache.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\draw\lv_img_decoder.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\layouts\flex\lv_flex.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\layouts\grid\lv_grid.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\lv_extra.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\themes\basic\lv_theme_basic.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\themes\default\lv_theme_default.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\themes\mono\lv_theme_mono.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\animimg\lv_animimg.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\calendar\lv_calendar.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\calendar\lv_calendar_header_arrow.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\calendar\lv_calendar_header_dropdown.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\chart\lv_chart.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\colorwheel\lv_colorwheel.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\imgbtn\lv_imgbtn.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\keyboard\lv_keyboard.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\led\lv_led.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\list\lv_list.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\meter\lv_meter.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\msgbox\lv_msgbox.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\span\lv_span.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\spinbox\lv_spinbox.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\spinner\lv_spinner.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\tabview\lv_tabview.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\tileview\lv_tileview.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\extra\widgets\win\lv_win.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_dejavu_16_persian_hebrew.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_fmt_txt.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_loader.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_10.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_12.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_12_subpx.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_14.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_16.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_18.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_20.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_22.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_24.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_26.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_28.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_28_compressed.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_30.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_32.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_34.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_36.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_38.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_40.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_42.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_44.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_46.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_48.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_montserrat_8.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_simsun_16_cjk.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_unscii_16.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\font\lv_font_unscii_8.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\gpu\lv_gpu_nxp_pxp.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\gpu\lv_gpu_nxp_pxp_osa.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\gpu\lv_gpu_nxp_vglite.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\gpu\lv_gpu_stm32_dma2d.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\hal\lv_hal_disp.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\hal\lv_hal_indev.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\hal\lv_hal_tick.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_anim.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_area.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_async.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_bidi.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_color.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_fs.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_gc.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_ll.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_log.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_math.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_mem.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_printf.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_style.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_style_gen.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_templ.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_timer.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_tlsf.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_txt.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_txt_ap.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\misc\lv_utils.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\widgets\lv_arc.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\widgets\lv_bar.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\widgets\lv_btn.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\widgets\lv_btnmatrix.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\widgets\lv_canvas.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\widgets\lv_checkbox.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\widgets\lv_dropdown.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\widgets\lv_img.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\widgets\lv_label.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\widgets\lv_line.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\widgets\lv_objx_templ.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\widgets\lv_roller.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\widgets\lv_slider.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\widgets\lv_switch.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\widgets\lv_table.o
Compiling .pio\build\emulator_64bits\libfaf\lvgl\widgets\lv_textarea.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\display\GC9A01.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\display\ILI9341.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\display\R61581.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\display\SHARP_MIP.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\display\SSD1963.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\display\ST7565.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\display\UC1610.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\display\drm.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\display\fbdev.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\display\monitor.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\gtkdrv\gtkdrv.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\indev\AD_touch.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\indev\FT5406EE8.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\indev\XPT2046.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\indev\evdev.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\indev\keyboard.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\indev\libinput.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\indev\mouse.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\indev\mousewheel.o
.pio\libdeps\emulator_64bits\lv_drivers\display\monitor.c:13:36: fatal error: SDL2/SDL.h: No such file or directory
 #  define MONITOR_SDL_INCLUDE_PATH <SDL2/SDL.h>
                                    ^
compilation terminated.
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\wayland\wayland.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\win32drv\win32drv.o
Compiling .pio\build\emulator_64bits\lib08d\lv_drivers\win_drv.o
Compiling .pio\build\emulator_64bits\hal\sdl2\app_hal.o
Compiling .pio\build\emulator_64bits\src\demo.o
Compiling .pio\build\emulator_64bits\src\img_bubble_pattern.o
*** [.pio\build\emulator_64bits\lib08d\lv_drivers\display\monitor.o] Error 1
hal\sdl2\app_hal.c:3:10: fatal error: SDL2/SDL.h: No such file or directory
 #include <SDL2/SDL.h>
          ^~~~~~~~~~~~
compilation terminated.
*** [.pio\build\emulator_64bits\hal\sdl2\app_hal.o] Error 1
In file included from .pio\libdeps\emulator_64bits\lv_drivers\indev\keyboard.c:9:
.pio\libdeps\emulator_64bits\lv_drivers\indev\keyboard.h:33:34: fatal error: SDL2/SDL.h: No such file or directory
 #define MONITOR_SDL_INCLUDE_PATH <SDL2/SDL.h>
                                  ^
compilation terminated.
*** [.pio\build\emulator_64bits\lib08d\lv_drivers\indev\keyboard.o] Error 1
In file included from .pio\libdeps\emulator_64bits\lv_drivers\indev\mouse.c:9:
.pio\libdeps\emulator_64bits\lv_drivers\indev\mouse.h:33:34: fatal error: SDL2/SDL.h: No such file or directory
 #define MONITOR_SDL_INCLUDE_PATH <SDL2/SDL.h>
                                  ^
compilation terminated.
*** [.pio\build\emulator_64bits\lib08d\lv_drivers\indev\mouse.o] Error 1
In file included from .pio\libdeps\emulator_64bits\lv_drivers\indev\mousewheel.c:9:
.pio\libdeps\emulator_64bits\lv_drivers\indev\mousewheel.h:33:34: fatal error: SDL2/SDL.h: No such file or directory
 #define MONITOR_SDL_INCLUDE_PATH <SDL2/SDL.h>
                                  ^
compilation terminated.
*** [.pio\build\emulator_64bits\lib08d\lv_drivers\indev\mousewheel.o] Error 1
============================================================= [FAILED] Took 9.08 seconds =============================================================

Environment      Status    Duration
---------------  --------  ------------
emulator_64bits  FAILED    00:00:09.082`

**Comment by reflector-li** [comment]
> PS. after some code change I succefully run it with v.8.0.1 here is my code: https://github.com/smarq8/lv_platformio-simulator-v8.0.1 ![LVGL simulator v 8 0 1 DEMO](https://user-images.githubusercontent.com/5141045/137637477-c473b5ed-062d-4ce8-9b30-2b6cd1eaad18.png)

Could you help me solve it? I download the code of your version, but it still reminds that the <SDL2/SDL.h> does not exist. 
![image](https://user-images.githubusercontent.com/51152320/144038894-c503db84-5642-47e4-8ad8-416e5bf774e8.png)

**Comment by smarq8** [comment]
did you install msys2 and SLD library?

see instruction at readme and msys2 installation guide [here](https://www.msys2.org/)

```
Windows

Use MSYS2

pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2

Add the path to your Mingw-w64 bin folder to the Windows PATH environment variable (usually C:\msys64\mingw64\bin). See instruction, 4.
```

**Comment by reflector-li** [comment]
> did you install msys2 and SLD library?
> 
> see instruction at readme and msys2 installation guide [here](https://www.msys2.org/)
> 
> ```
> Windows
> 
> Use MSYS2
> 
> pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2
> 
> Add the path to your Mingw-w64 bin folder to the Windows PATH environment variable (usually C:\msys64\mingw64\bin). See instruction, 4.
> ```

Thank you very much, I have installed them, and I had installed MinGW before. It may be confict with MSY32. Now I uninstalled the MinGW and only use the compiler in MSY32，and after restart the system, it works well.

**Comment by escherstair** [comment]
The pull request has been closed without merging (it seems so)

**Comment by richardclli** [comment]
I have made a pull request that works with LVGL v8.2
