### ISSUE TITLE
set background color of SDL main window

### ISSUE THREAD

**Issue by fo2w** [lvgl/lv_platformio#46]
I try to use below code to change the default white background color to black, but nothing happend.

```c
  lv_disp_set_bg_color(NULL, lv_color_black());
  lv_disp_set_bg_opa(NULL, LV_OPA_COVER);
```

Is there a bug of code, or limitation of simulator about it?

TYIA.

**Comment by puzrin** [comment]
Ask at lvgl forum please. This repo is about pio-specific things only.

**Comment by kisvegabor** [comment]
Please open an issue in the [main repo](https://github.com/lvgl/lvgl).
