### ISSUE TITLE
Can't find font

### ISSUE THREAD

**Issue by 2104788279** [lvgl/lv_platformio#47]
![image](https://user-images.githubusercontent.com/80264156/176398880-b6d98c7e-1d1c-4e90-ad1e-48620b2daeda.png)
![image](https://user-images.githubusercontent.com/80264156/176398969-32690adf-801c-4a89-b504-5a752cb1a8a2.png)
![image](https://user-images.githubusercontent.com/80264156/176399027-5ae3efc3-0293-4896-97e6-00fb2202b3c3.png)
![image](https://user-images.githubusercontent.com/80264156/176399052-7751da65-7ee3-4400-8ed1-70819ba80d1f.png)
Why does this compilation fail

**Comment by fbiego** [comment]
add `-D LV_FONT_MONTSERRAT_48` in the build_flags to include the font
