### ISSUE TITLE
Why does GCC compiler using ARM64 format on Apple silicon compile X86_64 format?

### ISSUE THREAD

**Issue by CNSTJiatongLee** [lvgl/lv_platformio#58]
I set platform=native on Mac M1 and it compiles using my native gcc compiler. Why is my native gcc compiler in ARM64 format and able to compile x86_64 files? This caused an error when linking to sdl2 in arm64 format that homebrew downloaded
<img width="800" alt="iShot_2024-01-27_23 56 29" src="https://github.com/lvgl/lv_platformio/assets/49759256/290a17d1-88c5-4e87-8e02-5ba1235b3fb2">
<img width="1291" alt="iShot_2024-01-27_23 57 00" src="https://github.com/lvgl/lv_platformio/assets/49759256/0bd0ac7f-ac06-4b2a-8be5-a47d9a69846e">
<img width="966" alt="iShot_2024-01-27_23 57 40" src="https://github.com/lvgl/lv_platformio/assets/49759256/04582350-176b-4576-b844-268f21fd98fc">

**Comment by tylerwowen** [comment]
I ran into the same problem. 

For my situation, the Platform IO installed was Darwin_x86_64. I don't know why it happened. My guess is that when I first installed the PlatformIO IDE extension, I was in a VSCode running in Intel mode, which could be a result of starting the VSCode from an Intel mode shell. 
```
pio  system info
--------------------------  ---------------------------------------------
PlatformIO Core             6.1.13
Python                      3.11.7-final.0
System Type                 darwin_x86_64
```

To fix, I did the following
1. Uninstall the PlatformIO ID extension from VSCode.
2. Remove the `$HOME/.platformio` created by the PlatformIO IDE
3. Reinstall the PlatformIO. Now I got the right version. 

```
pio  system info
--------------------------  ---------------------------------------------
PlatformIO Core             6.1.13
Python                      3.9.6-final.0
System Type                 darwin_arm64
```

**Comment by navanchauhan** [comment]
Just in case someone else stumbles upon this issue. I gave up on using the VSCode IDE and instead just installed paltformio via homebrew 

```
brew install platformio
```

I also had to change `python` to `python3` in the `platformio.ini` file (Or, you can set an alias from python -> python)

**Comment by fbiego** [comment]
Closing this issue as it’s resolved
