### ISSUE TITLE
Support lvgl released V9.0.0?

### ISSUE THREAD

**Issue by BlynkGO** [lvgl/lv_platformio#59]
I have tried to use lvgl v9.0.0 by lv_platformio, 
however it occurs some errors as the following

![image](https://github.com/lvgl/lv_platformio/assets/65327357/4bfaeeda-e521-41f8-96ae-fb9a1691553d)

How to solve them?
Thank you.

**Comment by kisvegabor** [comment]
Hi,

You can see how the API changed in v9 [here](https://docs.lvgl.io/master/CHANGELOG.html).

However in v9 there is a built in SDL driver that you can use very easily. See [here](https://github.com/lvgl/lv_port_pc_eclipse/blob/master/main.c#L111) and enable [here](https://github.com/lvgl/lv_port_pc_eclipse/blob/master/lv_conf.h#L832-L839).

**Comment by fbiego** [comment]
Closing this issue, feel free to reopen if you still have problems with v9
