### ISSUE TITLE
CAN NOT WORK ON WIN10!

### ISSUE THREAD

**Issue by linkua** [lvgl/lv_platformio#65]
Dependency Graph
|-- lvgl @ 9.1.0
Building in release mode
=====================================
Compiling .pio\build\emulator_64bits\libf53\lvgl\drivers\sdl\lv_sdl_keyboard.o
Compiling .pio\build\emulator_64bits\libf53\lvgl\drivers\sdl\lv_sdl_mouse.o
Compiling .pio\build\emulator_64bits\libf53\lvgl\drivers\sdl\lv_sdl_mousewheel.o
Compiling .pio\build\emulator_64bits\libf53\lvgl\drivers\sdl\lv_sdl_window.o
<command-line>: fatal error: SDL2/SDL.h: No such file or directory
compilation terminated.
*** [.pio\build\emulator_64bits\libf53\lvgl\drivers\sdl\lv_sdl_keyboard.o] Error 1
<command-line>: fatal error: SDL2/SDL.h: No such file or directory
compilation terminated.
*** [.pio\build\emulator_64bits\libf53\lvgl\drivers\sdl\lv_sdl_mouse.o] Error 1
<command-line>: fatal error: SDL2/SDL.h: No such file or directory
compilation terminated.
*** [.pio\build\emulator_64bits\libf53\lvgl\drivers\sdl\lv_sdl_mousewheel.o] Error 1
<command-line>: fatal error: SDL2/SDL.h: No such file or directory
compilation terminated.
*** [.pio\build\emulator_64bits\libf53\lvgl\drivers\sdl\lv_sdl_window.o] Error 1

**Comment by kisvegabor** [comment]
Have you followed the Windows guide [here](https://github.com/lvgl/lv_platformio?tab=readme-ov-file#install-sdl-drivers)?

**Comment by tylercamp** [comment]
I'm also having the same issue - I've installed MSYS2, ran the mentioned commands, and added `C:\msys64\mingw64\bin` to both System and User `PATH`. I can see `SDL2.dll` in that folder, and can see the `SDL2` folder in the adjacent `include` folder

---

Just after typing that I checked for any relevant config files in the repo folder on my machine, and in `.vscode/launch.json` I saw references to a `%USERPROFILE%/mingw` folder which I apparently prepared ~a year ago

After removing that from my `PATH` (and restarting VS Code) I was able to run the demo

**Comment by kisvegabor** [comment]
Happy that finally it's working.

> After removing that from my PATH (and restarting VS Code) I was able to run the demo

@linkua can you confirm it?

**Comment by brightproject** [comment]
> After removing that from my `PATH` (and restarting VS Code) I was able to run the demo

@kisvegabor and @tylercamp 

Unfortunately, there is an unclear and confusing line at the end of the instructions.
I don't understand why `MSYS2` should be launched in `Win10` using `pacman`?
On `Win10`, the build occurs with an error, but under `Win10` with `WSL1`, the build is performed without errors.

> https://github.com/lvgl/lv_platformio/issues/75

It seems to me that the [instructions](https://github.com/lvgl/lv_platformio?tab=readme-ov-file#install-visual-studio-code) for `Win10` need to be updated or removed altogether, they don’t work.

**Comment by tylercamp** [comment]
The note about `pacman` is directly from Microsoft's guidance on Windows https://code.visualstudio.com/docs/cpp/config-mingw#_prerequisites

Note that this is meant to be run within the msys2 CLI, I can find it by searching for `msys` in the start menu

**Comment by brightproject** [comment]
> mingw

https://github.com/lvgl/lv_platformio/issues/65#issuecomment-2966570466

Thank you? already fine🙂

> https://github.com/lvgl/lv_platformio/issues/75#issuecomment-2959945777
